apiVersion: v2
appVersion: 2.1.1
description: A Helm chart for the Woodpecker server
home: https://woodpecker-ci.org/
icon: https://avatars.githubusercontent.com/u/84780935?s=200&v=4
keywords:
- continuous-delivery
- continuous-deployment
- continuous-integration
- docker
- go
- kubernetes
maintainers:
- email: owner@woodpecker-ci.org
  name: Woodpecker Maintainers
  url: https://github.com/woodpecker-ci
name: server
sources:
- https://github.com/woodpecker-ci/woodpecker.git
type: application
version: 1.0.0
