apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.storage.class }}
  {{- if (eq "-" .Values.storage.class) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.storage.class }}"
  {{- end }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
