apiVersion: v2
appVersion: 2.1.1
dependencies:
- condition: server.enabled
  name: server
  repository: ""
  version: 1.0.0
- condition: agent.enabled
  name: agent
  repository: ""
  version: 0.2.0
description: A Helm chart for Woodpecker CI
home: https://woodpecker-ci.org/
icon: https://avatars.githubusercontent.com/u/84780935?s=200&v=4
keywords:
- continuous-delivery
- continuous-deployment
- continuous-integration
- docker
- go
- kubernetes
maintainers:
- email: owner@woodpecker-ci.org
  name: Woodpecker Maintainers
  url: https://github.com/woodpecker-ci
name: woodpecker
sources:
- https://github.com/woodpecker-ci/woodpecker.git
- https://github.com/woodpecker-ci/helm.git
type: application
version: 1.0.3
