---
name: Helm
on:
  push:

jobs:
  helm-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          echo changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }}) > "${GITHUB_OUTPUT}"

      - name: Create pull request
        id: create-pr
        if: github.ref != 'refs/heads/main'
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          title: "Mirror ${{ steps.list-changed.outputs.changed }}"
          branch: ${{ github.ref }}
          base: main

      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
      
      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed != ''
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed != ''
        uses: helm/kind-action@v1.7.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed != ''
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (upgrade)
        if: steps.list-changed.outputs.changed != ''
        run: ct install --target-branch ${{ github.event.repository.default_branch }}  --upgrade

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release charts
        if: github.ref == 'refs/heads/main'
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

